mysite/myauth/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import (
    main_page_view,
    RegisterView,
    ProfileUpdateView,
    UserDetailView,
    UserListView,
    AvatarUpdateView,
)


from .views import (
    AboutMeView,
)

app_name = "myauth"

urlpatterns = [
    path("main-page/", main_page_view, name="main_page"),
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login"
    ),
    path(
        "logout/",
        LogoutView.as_view(),
        name="logout"
    ),
    path(
        "register/",
        RegisterView.as_view(),
        name="register",
    ),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("about-user/<int:pk>", UserDetailView.as_view(), name="about-user"),
    path("user-list/", UserListView.as_view(), name="user-list"),
    path("update-profile/", ProfileUpdateView.as_view(), name="update-profile"),
    path("update-avatar/<int:pk>", AvatarUpdateView.as_view(), name="update-avatar")
]

mysite/myauth/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


def avatars_dir_path(instance: "Profile", filename: str) -> str:
    return "myauth/user_{pk}/avatar/{filename}".format(
        pk=instance.user.pk,
        filename=filename,
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    biography = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=True)
    avatar = models.ImageField(
        null=True, upload_to=avatars_dir_path
    )


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

mysite/myauth/forms.py
from django import forms

from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "biography", "agreement_accepted"

mysite/myauth/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, TemplateView, ListView, DetailView
from django.http import HttpRequest, HttpResponse
from django.urls import reverse_lazy, reverse

from .models import Profile


def main_page_view(request: HttpRequest) -> HttpResponse:
    return render(request, "myauth/main-page.html")


class AboutMeView(LoginRequiredMixin, TemplateView):
    template_name = "myauth/about-me.html"


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)

        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    fields = "biography", "agreement_accepted", "avatar"
    template_name = "myauth/profile_update.html"
    success_url = reverse_lazy("myauth:about-me")

    def get_object(self, queryset=None):
        return self.request.user.profile


class UserListView(ListView):
    queryset = User.objects.select_related("profile")
    template_name = "myauth/user_list.html"


class UserDetailView(DetailView):
    queryset = User.objects.select_related("profile")
    template_name = "myauth/about-user.html"
    context_object_name = "object"


class AvatarUpdateView(UserPassesTestMixin, UpdateView):
    model = Profile
    fields = "avatar",
    template_name = "myauth/avatar_update.html"

    def get_success_url(self):
        return reverse(
            "myauth:about-user",
            kwargs={"pk": self.object.pk},
        )

    def test_func(self):
        return self.request.user.is_staff or self.get_object().pk == self.request.user.pk

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/main-page.html' %}

{% block title %}
  About me
{% endblock %}

{% block page %}
  <section class="page">
  <h1>User info</h1>
  {% if user.is_authenticated %}
    <h2>Detail</h2>
    <p>
        {% if user.profile.avatar %}
        <img src="{{user.profile.avatar.url}}"
             alt="{{user.profile.avatar.name}}"
             width="200"
        >
        {% else %}
        No avatar
        {% endif %}
    </p>
    <p>Username: {{ user.username }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Bio: {{ user.profile.biography }}</p>
    <a href="{% url 'myauth:update-profile' %}">
        <button class="orange_button" type="button">Update</button>
    </a>
  {% else %}
    <h2>User is anonymous</h2>
  {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/about-user.html
{% extends 'myauth/main-page.html' %}

{% block title %}
  About me
{% endblock %}

{% block page %}
  <section class="page">
  <h1>User info</h1>
    <h2>Detail</h2>
    <p>
        {% if object.profile.avatar %}
        <img src="{{object.profile.avatar.url}}"
             alt="{{object.profile.avatar.name}}"
             width="200"
        >
        {% else %}
        No avatar
        {% endif %}
        {% if user.is_staff or object.pk == user.pk %}
        <a href="{% url 'myauth:update-avatar' pk=object.pk%}"> Change avatar</a>
        {% endif %}
    </p>
    <p>Username: {{ object.username }}</p>
    <p>First name: {{ object.first_name }}</p>
    <p>Last name: {{ object.last_name }}</p>
    <p>Email: {{ object.email }}</p>
    <p>Bio: {{ object.profile.biography }}</p>
    <p><a href="{% url 'myauth:user-list' %}">Back</a></p>
{% endblock %}

mysite/myauth/templates/myauth/avatar_update.html
{% extends 'myauth/main-page.html' %}

{% block title %}
  Update profile
{% endblock %}


{% block page %}
  <section class="page">
  <h1>Update avatar</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Avatar</p>
        <p>{{form.avatar}}</p>
        <button class="orange_button" type="submit">Update</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/login.html
{% extends "myauth/base.html" %}
{% load static %}

{% block title %}
Login
{% endblock %}

{% block body %}
<div class="login">
<h1 align="center">Mysite</h1>
<h2>{% block welcome %}Please, log in{% endblock %}</h2>
  <form method="post">
    {% csrf_token %}
    {{form.non_field_errors}}
    {% for field in form %}
    <div>
      {{fields.errors}}
      <p>{{field.label_tag}}</p>
      <p>{{field}}</p>
      {% if field.help_text %}
        <p>{{field.help_text|safe}}</p>
      {% endif %}
    </div>
    {% endfor %}
    <button class="orange_button" type="submit">{% block button_text %}Login{% endblock %}</button>
    {% block login_or_register %}
    <a href="{% url 'myauth:register' %}"><button class="orange_button" type="button">Register</button></a>
    {% endblock %}
  </form>
</div>
{% endblock %}

mysite/myauth/templates/myauth/main-page.html
{% extends 'myauth/base.html' %}

{% block title %}
  Mysite
{% endblock %}


{% block body %}
<header>
    <div class="site-name">
    <h1>Mysite</h1>
    </div>
    <div class="refs">
        <div class="menu">
            <div>
                <a href="{% url 'myauth:about-me' %}">Profile</a>
            </div>
            <div>
                <a href="{% url 'myauth:user-list' %}">Users</a>
            </div>
            <div>
                <a href="{% url 'shopapp:products_list' %}">Products</a>
            </div>
            <div>
                <a href="{% url 'shopapp:orders_list' %}">Orders</a>
            </div>
        </div>
        <div class="log-butttons">
          {% if user.is_authenticated %}
            <div>Hello, {{user.username}}!</div>
            <div>
              <form method="post" action="{% url 'myauth:logout' %}">
              {% csrf_token %}
              <button class="orange_button" type="submit">Logout</button>
              </form>
            </div>
          {% else %}
            <div>
              <form method="post" action="{% url 'myauth:login' %}">
                {% csrf_token %}
                <button class="orange_button" type="submit">Login</button>
              </form>
            </div>
            <div>
              <form method="post" action="{% url 'myauth:register' %}">
                {% csrf_token %}
                <button class="orange_button" type="submit">Register</button>
              </form>
            </div>
          {% endif %}
        </div>
    </div>

</header>
  {% block page %}
  <section>
    <h2>Main page</h2>
  </section>
  {% endblock %}
{% endblock %}

mysite/myauth/templates/myauth/profile_update.html
{% extends 'myauth/main-page.html' %}

{% block title %}
  Update profile
{% endblock %}


{% block page %}
  <section class="page">
  <h1>Update profile</h1>
  {% if user.is_authenticated %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Avatar</p>
        <p>{{form.avatar}}</p>
        <p>Biography</p>
        <p>{{form.biography}}</p>
        <p>Agreement accepted: {{form.agreement_accepted}}</p>
        <button class="orange_button" type="submit">Update</button>
    </form>
  {% else %}
    <h2>User is anonymous</h2>
  {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends "myauth/login.html" %}

{% block title %}Register{% endblock %}
{% block welcome %}Please, sign up{% endblock %}
{% block button_text %}Register{% endblock %}
{% block login_or_register %}
<a href="{% url 'myauth:login' %}"><button class="orange_button" type="button">Login</button></a>
{% endblock %}

mysite/myauth/templates/myauth/user_list.html
{% extends 'myauth/main-page.html' %}

{% block title %}
  Users List
{% endblock %}

{% block page %}
  <section class="page">
      <h1>Users list</h1>
        <ul>
          {% for user in object_list %}
            <li>
                <a href="{% url 'myauth:about-user' pk=user.pk %}">
                    <p>
                        {% if user.profile.avatar %}
                        <img src="{{user.profile.avatar.url}}" alt="{{user.profile.avatar.name}}" width="200">
                        {% endif %}
                    </p>
                    <p>{{user.username}}</p>
                </a>
            </li>
          {% endfor %}
        </ul>

{% endblock %}